baseurl = "http://nik.nickmcavoy.com/"
languageCode = "en-us"
title = "닉: Nick in Korea"
theme = "vienna"

[params]
Author = "Nick McAvoy"
DateForm = "Jan 2, 2006"
Description = "닉: Nick in Korea"
Email = "nicholas.mcavoy@gmail.com"
GitHub = "//github.com/ohbadiah"
Twitter = "@ohbadiah"
FaviconFile = "img/favicon.png"
previewimage = "img/default.jpg"
description = "Nick went to Korea, and this is what he wrote about it."
